version: "3.8"

services:
  db:
    image: mysql:8.0.25
    container_name: heros-mysql
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: heros-phpmyadmin
    ports:
      - "8082:80"
    restart: always
    environment:
      PMA_HOST: db

  spring:
    image: nathan/heros-spring
    container_name: heros-spring
    build:
      context: ..
      dockerfile: .docker/heros-app/Dockerfile
    depends_on:
      - db
    ports:
      - "8083:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.properties.hibername.jdbc.time_zone" : "UTC",
        "spring.jpa.database" : "$MYSQLDB_JPA_DATABASE",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - ${APPLICATION_ROOT_FOLDER}:/var/heros-app
    restart: on-failure

volumes:
  dbdata: